### ISSUE TITLE
enable snapshots?

### ISSUE THREAD

**Issue by zazi** [jexp/neo4j-mapdb-index#3]
I'm struggling with upgrading this mapdb index provider implementation to neo4j 2.0.1 and mapdb 0.9.11
I'm always getting the following error:
```
java.lang.UnsupportedOperationException: Snapshots are not enabled, use DBMaker.snapshotEnable()
	at org.mapdb.TxEngine.createSnapshotFor(TxEngine.java:72) ~[mapdb-index-1.0-jar-with-dependencies.jar:na]
	at org.mapdb.BTreeMap.snapshot(BTreeMap.java:2752) ~[mapdb-index-1.0-jar-with-dependencies.jar:na]
	at org.neo4j.index.mapdb.MapDbSchemaIndexProvider$MapDbIndex.newReader(MapDbSchemaIndexProvider.java:243)
```
albeit, I'm initialising the mapdb instance with
```
db = DBMaker.newFileDB(getIndexFile(config)).compressionEnable().asyncWriteFlushDelay(1).closeOnJvmShutdown().snapshotEnable().make();
```
I can run your tests successfully, however, when I deploy it to my stand-alone installation and try to run it with my unmanaged extension, then it doesn't work and I'm getting the error from above.
Thx a lot in advance for your help.

**Comment by zazi** [comment]
any update on this issue, since it still seems to be alive when I run the tests with @russwyte's fork (https://github.com/russwyte/neo4j-mapdb-index):

````
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.845 sec <<< FAILURE! - in org.neo4j.index.mapdb.MapDbIndexTest
testCreateAddIndex(org.neo4j.index.mapdb.MapDbIndexTest)  Time elapsed: 0.634 sec  <<< ERROR!
java.lang.UnsupportedOperationException: Snapshots are not enabled, use DBMaker.snapshotEnable()
	at org.mapdb.TxEngine.createSnapshotFor(TxEngine.java:72)
	at org.mapdb.BTreeMap.snapshot(BTreeMap.java:2752)
	at org.neo4j.index.mapdb.MapDbSchemaIndexProvider$MapDbIndex.newReader(MapDbSchemaIndexProvider.java:244)
	at org.neo4j.kernel.impl.api.index.OnlineIndexProxy.newReader(OnlineIndexProxy.java:104)
	at org.neo4j.kernel.impl.api.index.FlippableIndexProxy.newReader(FlippableIndexProxy.java:184)
	at org.neo4j.kernel.impl.api.index.AbstractDelegatingIndexProxy.newReader(AbstractDelegatingIndexProxy.java:92)
	at org.neo4j.kernel.impl.api.IndexReaderFactory$Caching.newUnCachedReader(IndexReaderFactory.java:68)
	at org.neo4j.kernel.impl.api.IndexReaderFactory$Caching.newReader(IndexReaderFactory.java:59)
	at org.neo4j.kernel.impl.api.KernelStatement.getIndexReader(KernelStatement.java:144)
	at org.neo4j.kernel.impl.api.store.DiskLayer.nodesGetFromIndexLookup(DiskLayer.java:435)
	at org.neo4j.kernel.impl.api.store.CacheLayer.nodesGetFromIndexLookup(CacheLayer.java:326)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodesGetFromIndexLookup(StateHandlingStatementOperations.java:459)
	at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodesGetFromIndexLookup(ConstraintEnforcingEntityOperations.java:199)
	at org.neo4j.kernel.impl.api.OperationsFacade.nodesGetFromIndexLookup(OperationsFacade.java:135)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.nodesByLabelAndProperty(InternalAbstractGraphDatabase.java:1504)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.access$300(InternalAbstractGraphDatabase.java:185)
	at org.neo4j.kernel.InternalAbstractGraphDatabase$8.iterator(InternalAbstractGraphDatabase.java:1478)
	at org.neo4j.kernel.InternalAbstractGraphDatabase$8.iterator(InternalAbstractGraphDatabase.java:1474)
	at org.neo4j.helpers.collection.IteratorUtil.single(IteratorUtil.java:305)
	at org.neo4j.index.mapdb.BasicIndexTest.testCreateAddIndex(BasicIndexTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
````
